name = "EEGPlot"
uuid = "7b5c3b30-84a4-4b07-a630-c21dc8c95940"
authors = ["Marco Congedo, Tomas Ros, Generative AI"]
version = "0.0.4"

[deps]
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
ImageClipboard = "6db54171-f50f-4661-a74f-bc514ef16cee"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
GLFW = "3.4.6"
ImageClipboard = "1.0"
Makie = "0.24.8"
Statistics = "1.11"
julia = "1.11"
